### ISSUE TITLE
Documents encryption

### ISSUE THREAD

**Issue by geakstr** [share/sharedb#107]
I want to store encrypted data in database. May be it's possible to implement it with middleware, for example?

**Comment by sferoze** [comment]
I am using the quill editor. It uses delta object to represent changes in the document.

I tried using cryptoJS to encrypt the delta on `submitOp` and then decrypting the received operations on the `op` event. 

It works and the information is encrypted upon sending and decrypted upon arrival but there are issues. The issue is that the encryption and the decryption takes time, so as a user is typing the operation can't keep up and insert get added in the wrong places....

Not sure how to solve this. Would be nice if sharedb had a transform hook, to apply a transformation on ops that are sent and received.
