### ISSUE TITLE
Multi-threaded ShareDB

### ISSUE THREAD

**Issue by kbadk** [share/sharedb#110]
Does ShareDB support multiple instances running at the same time by using something like [Cluster](https://nodejs.org/api/cluster.html)?

**Comment by DetweilerRyan** [comment]
Good question, and the answer is yes, but it requires a little bit of work.  In order to mitigate the inevitable collisions resulting from more than one instance of a ShareDB server you need to use a supported PubSub adapter when configuring ShareDB.  The example below uses the supported redis pubsub adapter which, of course, requires redis.

`
var ShareDb = require('sharedb');
var shareDbMongo = require('sharedb-mongo');
var shareDbRedisPubSub = require('sharedb-redis-pubsub');

var share = ShareDb( {
  db: shareDbMongo('localhost:27017/test'),
  pubsub: shareDbRedisPubSub('localhost:6379/test')
} );
`

Now you can you can use any mechanism you like for managing a pool of ShareDB instances including Cluster.

**Comment by kbadk** [comment]
Thnk you!
