### ISSUE TITLE
Pass projection-name instead of target-collection in Backend.fetch

### ISSUE THREAD

**Issue by ChrisSG** [share/sharedb#111]
In sharedb-access you can't implement access control to projections but to collections only. Changing colelction to index in

`backend._sanitizeSnapshot(agent, snapshotProjection, collection, id, snapshot, function(err) `

like

`backend._sanitizeSnapshot(agent, snapshotProjection, index, id, snapshot, function(err) `

would solve the problem. Would this introduce implications?

**Comment by curran** [comment]
I'd love to be able to implement access control on projections as well as the original collections. The proposed change sounds like a Good Thing to me.

**Comment by nateps** [comment]
I totally understand the motivation of the request, though this was intentional.

It can be a liability to have adding a new projection expose data with a new name, since then your access control code might miss cases when another developer on your team adds a new projection and doesn't realize the new projection is not guarded by the access rules. For now, using the actual collection name at least makes you aware that you should explicitly check that certain fields are not getting exposed to the client. It is a bit more code, but it is safer to check the doc / ops being returned for the data that you want to protect from going to the client than to do it by projection name.

The current projections implementation where it is a virtual collection that has a different name from the real collection is something we are hoping to replace with the ability to pass in a specific projection with each query, as you would in a normal database query. The current implementation is better than nothing, but it is very difficult to work with the collection name being different for different queries of the same objects. Since I'd like to change this in the next major version, I tried to keep the exposure of projection names to the current API minimal.

As we improve projections, we'll take the access control angle into consideration and try to come up with an easier to use solution. For now, I recommend using the 'doc' middleware and 'op' middleware to return errors if users try to access fields that the should not have access to.

**Comment by ChrisSG** [comment]
Just did a fresh install of the newest derbyjs with sharedb and it seems that the newest version just does that. It exposes the projection-name now, not the collection-name?!

**Comment by nateps** [comment]
sharedb-access apparently looks for an `index` property and uses that instead of the collection when available. This is set in the submit/commit/apply middleware that are part of writing but not on reading ops or docs. I'd recommend just using the collection name for the previously mentioned reasons.
