### ISSUE TITLE
sharedb : Is possible apply for an app spreadsheets ?

### ISSUE THREAD

**Issue by serip88** [share/sharedb#125]
Hi Bro,

Example I want to build an app look like https://docs.google.com/spreadsheets/
sharedb is suitable to do that ?
I mean problem is handle data on each cell .  1000 cell is difference with an editor like quilljs, is it right ? and is it possible ? 

Thanks !

**Comment by curran** [comment]
Here's a table example with DerbyJS https://github.com/derbyjs/derby-examples/blob/master/sink/views/table.html

It's possible to represent a spreadsheet inside a ShareDB document, it's just a question of how you represent the data. Each document could contain a spreadsheet as an array of arrays, or as an array of row objects, or other representations (e.g. CSV string).

**Comment by roark** [comment]
Depending on one's use case I think there could be an issue with representing a table using an array of arrays with the json0 OT type.

That issue would present itself if someone adds a column while someone else simultaneously adds a row. The json0's transform function wouldn't correctly handle the intent of such a case... In that case the table would be missing a single cell, since the new row added would only account for the columns that existed on its creation and visa versa for the new column added.

I believe the only correct way to truly represent tables in the system is to build a separate OT type. I've been considering building such a type in the near future.

The ot-table type that would contain the ops: "add row", "add column", "delete row", "delete column", "move row", "move column"... The transform function would correctly handle a new row and new column being added at the same time. Each table cell would contain an embedded subtype. 

In the future a more complex op such as "merge cells" would be nice. However that would require that the ot-table type having a better understanding of the underlying embedded subtype that its cells are using. (That way it could correctly merge the contents in an OT fashion)

**Comment by curran** [comment]
I had an idea for a data structure that could represent spreadsheets and be robust under OT.

The idea is that a table is represented with two arrays:

 * `rows` An array of objects, each of which contains all values for a single row. Keys can be integers.
 * `columns` An array of row key integers. This determines the ordering of columns.

As an example, consider a simple table that would look like this in CSV:

```
name,age
Bob,30
Jim,20
Jane,25
```

The data structure could look like this:

```json
{
  "columns": [0, 1]
  "rows": [
    { "0": "name", "1": "age" },
    { "0": "Bob", "1": 30 },
    { "0": "Jim", "1": 20 },
    { "0": "Jane", "1": 25 }
  ]
}
```

Empty table cells would be represented by no key present.

Operations:

 * Adding a row would add an empty object to the `rows` array.
 * Reordering of rows would be straightforward reordering of the `rows` array.
 * Deleting a row would be straightforward array element deletion.
 * Adding a column would add an integer to the `columns` array (could be inserted at any position) and would be straightforward array insertion.
 * Reordering of columns would be straightforward reordering of the `rows` array (no need to change any  row objects).
 * Deleting a column would be the most involved operation. It would require straightforward array element deletion from the `columns` array, and also deletion of the corresponding key for all of the row objects. If the `columns` array is considered as the source of truth for the ordered list of columns present, then keeping around old keys in the rows would not impede functionality. It could kind of be treated as garbage collection, not necessarily done at the time of the original operation, where some process periodically checks for orphaned keys and deletes them.

**Comment by serip88** [comment]
@roark : thank for your information about json0 OT type,
I think I will try to build a simple app with a simple way


@curran: thank for share example and "database structure", it will be good for reference

@roark @curran
And some more question about json0

1. I used **submitOp()** with this object

```
var cell = [{p: ['value'], od: "", oi: "new value"},
        {p: ['id'], od: "", oi: 1234},
        {p: ['row'], od: "", oi: 1 },
        {p: ['column'], od: "", oi: "C"},
        {p: ['column_int'], od: "", oi: 3},
        {p: ['user_no'], od: "", oi: 345}];
```

// with od:"" is any value I don't care if new value and old value is same

+ I received 6 response, I just want use "var cell" like "mediate" object to sync data to another brower and I just want to received 1 response to get full data submitOp(), is this posible?
+ because I need id and some information of "var cell" to update cell edited  in another brower (border, new value, who are keeping this cell id)
+ and server.js I will use a "driver" to update table depend "id" I passed in  submitOp(cell), but i'm not sure this is good way
+ i'm newbie and I think I will use mysql because I'm not familiar with mongodb and I don't know for sure about the compatibility between mongodb and node module compare with another database type
+ and last:  is there any problem with performance or json0 when submitOp an object response one time? 
Plz give me some suggestion to design, because this is the first time I'm research node_modules , 
so I'm not sure I  was choose a good way to build an application in the right way

_Thanks you very much_

**Comment by roark** [comment]
HI @curran,

Thanks for sharing your idea on an ot-table data structure. It's a very clever design and one that also resolve the issue I'd mentioned above in regards to using the json0.

With your structure, one could use the json0 type and if **User1** added a column, while simultaneously **User2** added a row, the structure would remain completely valid. Since the row added would be an empty array and the column added would simply be an identifier.

There are 2 relevant points that came to my mind.

1. When building an add column op, one should generate a UUID as the column ID to minimize any chance of column ID collision.
2. It could be possible that several rogue cells end up sporadically throughout the data structure. If **User1** is inserting new (previously empty) cell content at `row5 / column5` and **User2** is simultaneously removing `column5`. **User2**'s op would not remove the new cell that was added by **User1**, since it wasn't there when the op was originally generated. (a custom transformation would solve this)

That said, there are probably some relatively simple work arounds that one could implement to make it all work now with json0.
- Rogue cells would not be displayed in the interface.
- Worker process could occasionally look through the db snapshots for rogue cells and generate the ops to remove them.

Since this structure has many benefits in terms of computation speed, it would be a great structure wrapped in its own OT type. If only to resolve the rogue cell case with an appropriate transform function.
