### ISSUE TITLE
client uses process.nextTick instead of async.nextTick

### ISSUE THREAD

**Issue by zacharyclaysmith** [share/sharedb#136]
I'm running into issues where "process" isn't defined in the browser, specifically in the `connection` file. Is there a reason the library uses `process.nextTick` instead of `async.nextTick`, which I think would be more compatible with the browser?

**Comment by rkstedman** [comment]
Hello! I'm not sure of the original reasoning around using process vs async nextTick, but I can recommend a way to solve your issues with running ShareDB in the browser.

In order to use ShareDB from a browser, you need to use a client bundler like Browserify or Webpack. This should solve the "process" not being defined issue.

**Comment by zacharyclaysmith** [comment]
Thanks, some background I'm using the angular2-webpack-starter project, which recently changed its prod config pretty majorly. Now I'm trying to figure out if it caused problems with this library or revealed them, aka, npm development :P.

**Comment by rkstedman** [comment]
Oh, good luck! Feel free to write in with additional questions you have. I'll try and help if I can.

**Comment by zacharyclaysmith** [comment]
Closing this issue as it seems like a non-issue. Thanks for your insight :)!
