### ISSUE TITLE
rich-text subtype of json0

### ISSUE THREAD

**Issue by darioAnongba** [share/sharedb#149]
Hello,

I'm trying to use ShareDB to store a JSON document (representing a form) with a "rich-text" field as a subtype. Sadly, I got an error because the type "rich-text" does not have a function "invert".
This is the error:
```
Uncaught TypeError: subtypes[c.t].invert is not a function at json0.js:74
```
The operation passed to the document of type "json0" is of the form:

```JavaScript
const op = [{p:['myRichTextField'], t:'rich-text', o:Delta}]
```

Is this a bug or can I find another way to implement this ?

I hope to get an answer since this repo seems to be dead.

Thank you for your time.

**Comment by darioAnongba** [comment]
Yeah because for the moment the type "rich-text" is not actually a subtype as defined in ottypes.
I will keep this issue open just in case.

**Comment by pedrosanta** [comment]
Seems like `invert` is optional for ottypes: https://github.com/ottypes/docs#optional-properties

And `rich-text` really doesn't provide an `invert` method, which [seems to be by design](https://github.com/ottypes/rich-text/issues/21).

I don't know where should be the best place to discuss if [ottypes/rich-text issues](https://github.com/ottypes/rich-text/issues) or [ShareJS mailing list](https://groups.google.com/forum/#!forum/sharejs). Anyway, I would say that for any of this Jason Chen seems to be the guy to reach to.

**Comment by darioAnongba** [comment]
Thanks ! I will try to reach him. and maybe tag him here so he can see this thread.
@jhchen

**Comment by jhchen** [comment]
Yes `rich-text` is not invertible

**Comment by pedrosanta** [comment]
Also relevant it's this discussion @darioAnongba: https://groups.google.com/forum/#!topic/sharejs/QaUmRaVpJ1w

**Comment by sferoze** [comment]
@pedrosanta hey, I've been able to work with rich text type and found a way to undo and redo, without needing invert. Let me know your thoughts. I basically get all the ops for the document. Group the operations in batches of 10, and then push to history stack. Very similar to how quill history module does it. 

```coffeescript
    results = getAllOpsForDocumentId(id)
    oldsnapshot = null
    snapshot = null

    _.each results, (op, index) ->
      ob = {}
      return if index is 0 and op.create
      previousOp = results[index - 1]
      if previousOp.create?
        snapshot = RichText.type.create(previousOp.create.data)
      oldsnapshot = _.clone snapshot
      snapshot = RichText.type.apply snapshot.ops, op.op.ops
      undoDelta = snapshot.diff(oldsnapshot)
      changeDelta = RichText.type.deserialize op.op.ops
      timestamp = Date.now()
      if (index % 10) isnt 0 and t.editor.history.stack.undo.length > 0
        delta = t.editor.history.stack.undo.pop()
        undoDelta = undoDelta.compose(delta.undo)
        changeDelta = delta.redo.compose(changeDelta)

      t.editor.history.stack.undo.push
        redo: changeDelta
        undo: undoDelta
```

**Comment by pedrosanta** [comment]
@sferoze but where do you have this code? So you managed to get `rich-text` as a sub-type of `json0`? This means we would need to update the `rich-text` format with a similar code?

Could you go over it in a bit more detail? 🙂

**Comment by sferoze** [comment]
@pedrosanta 

I am not able to get rich-text as a sub-type of json0 because of this: https://github.com/ottypes/rich-text/issues/21#issuecomment-227562091

It is not as easy or efficient as invert and it is required that you get all ops starting from version 0

But you can achieve a similar result with the code I posted. 

To get this to work I took a look at how Quill's history module works. With Quill's history module you can undo and redo. And since quill uses rich text undo is possible. 

To get the undo delta, you have to diff 2 Delta Documents. A Delta Document is returned with quill.getContents() 

Delta documents are different from Delta operations although they both use the same Delta object. Delta operation is returned to the text-change event representing single operation. 

But to get the undo you have to diff 2 documents. The old document and the new document. 

Since all operation are stored with sharedb you can build up the document to any point in its history. This is what is shown in the code I posted. It diffs the old snapshot and new snapshot and builds up each undo operation. It pushes these undo operations into Quill's history stack. 

I decided to batch together 10 operations and make every 10 operations an undo operation. 

That is the gist of how it works. Let me know if you have any questions... and if you notice any way to improve it def let me know!
