### ISSUE TITLE
add custom actions

### ISSUE THREAD

**Issue by dcharbonnier** [share/sharedb#177]
It would be very convenient to be able to add custom actions, the project https://github.com/BBWeb/racer-rpc is not for sharedb and is a dirty hack.
Adding this at the share db level would be very convenient.
Being able to stop a request propagation on the "receive" middleware could be enough to make this possible.

**Comment by curran** [comment]
What do you mean by "custom actions"?

**Comment by dcharbonnier** [comment]
being able to register some hanglers for new values of request.a like "auth" for example or at least one handler for unexpected messages

**Comment by dcharbonnier** [comment]
on the server side Iwrote my own WebSocketJsonStream to filter the objects... for the client side I can register a listener for all messages but I will keep receiving a warning

```

    private connection(ws: WebSocket) {
        const stream = new WebSocketJsonStream(ws);
        const agent = this.context.backend.addClient(stream);
        stream.filter = ((obj: any) => {
            if (obj.a && obj.a === "custom") {
                this.handleAction(agent, obj.type, obj);
                return false;
            }
            return true;
        });
    }

    private handleAction(agent: any, type: string, obj: any) {
        if (type === "auth") {
            agent.custom = {auth: true, limits: JSON.parse(obj.token)}; // @todo
            agent.send("authenticated");
        } else {
            this.context.logger.warn(`Unknown custom action ${type}`);
        }
    }
```

**Comment by DetweilerRyan** [comment]
Correct me if I'm wrong, @dcharbonnier, but it sounds like you want to use the existing websocket that sharedb uses to send you're own messages without having to open a second websocket. It is definitely better to reuse the existing websocket instead of creating another websocket just to send and receive you're own messages. And it's unfortunate that ShareDb completely takes over the websocket; however, there is a way ( more of a hack) to effectively namespace messages sent to and from sharedb on a single websocket that you can use to send and receive you're own messages without any conflict. If this is indeed your problem then I am happy to share the solution with you.

**Comment by dcharbonnier** [comment]
thx, I manage to hack it @DetweilerRyan but I think this should be available without "hack"

**Comment by curran** [comment]
I think this can be closed as out-of-scope for the project, unless either of you can propose a concrete API change to ShareDB. Thanks!

**Comment by dcharbonnier** [comment]
Solved with https://github.com/dcharbonnier/advanced-websocket

**Comment by curran** [comment]
That's amazing!

Maybe we could add a link to this in the ShareDB README.

**Comment by dcharbonnier** [comment]
wait for a version 0.1 of this project at least, for now its not 100% working but in less than a week it should be ready

**Comment by dcharbonnier** [comment]
the version 0.2.0 that I just published it working with sharedb, see the example on the readme

**Comment by yaroslavputria** [comment]
Guys, do you know how custom messages can be imlemented on the redis scaled sharedb? One of the sharedb back-end instances should invoke sending messages to all clients (which can be connected to different back-end instances).
