### ISSUE TITLE
EventSource instead of websocket

### ISSUE THREAD

**Issue by jschatz1** [share/sharedb#180]
I haven't found any example, and I am willing to write my own, but is it possible to use EventSource instead of websockets?

https://developer.mozilla.org/en-US/docs/Web/API/EventSource

**Comment by josephg** [comment]
Technically? Absolutely. I'm not sure if the current codebase supports it, but I've written compatible OT things on top of eventsource before. You'd need to fall back to POSTs or something to send ops back toward the server. And because of connection limits you'd need to be able to multiplex everything through a single eventsource. So there's some moving parts you'd need to make it work well.

**Comment by rkstedman** [comment]
Thanks for your question! I'm closing this issue since it seems Joseph has answered your question -- however, feel free to reopen if you have any further questions or clarifications @jschatz1!
