### ISSUE TITLE
Support for multiple subscriptions

### ISSUE THREAD

**Issue by derekjgrove** [share/sharedb#190]
When multiple subscriptions are fired, we get the following warning:
warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.

Is there a way to control this and avoid memory leaks?

Thanks,
Derek

**Comment by curran** [comment]
I've found this error happens when you want to switch subscriptions from one document to another multiple times, but don't unsubscribe first to clean up the old subscription. Are you unsubscribing? Can you provide more detail for what your code is doing?

You can definitely have multiple subscriptions without getting this error.

**Comment by curran** [comment]
I think this issue can be closed. ShareDB supports multiple subscriptions.

**Comment by curran** [comment]
I vote to close this due to inactivity.

The solution is to use `doc.destroy()`, `query.destroy()`, and `doc.removeListener()` where appropriate to clean things up.

**Comment by ericyhwang** [comment]
Thanks for answering, Curran!

As another piece of anecdotal evidence, we use doc and query subscriptions extensively in our production services and haven't noticed any ShareDB memory leaks.

I'll close this for now. Feel free to reopen with an example if you're still seeing these after using the cleanup methods where needed, or if it's unclear when to use them.
