### ISSUE TITLE
remove the stream even listeners on end

### ISSUE THREAD

**Issue by dcharbonnier** [share/sharedb#208]
if the stream emit more than one `end` event we have an incorrect number of agentsCount, the stream should not emit more than one event but we should use `once` instead of `on` and remove the listeners on _clean

**Comment by gkubisa** [comment]
It looks like one `end` event comes from [here](https://github.com/avital/websocket-json-stream/blob/master/index.js#L13) and the duplicate `end` event from [here](https://github.com/avital/websocket-json-stream/blob/master/index.js#L17). So, the problem is actually with websocket-json-stream and the fix is to remove [this line](https://github.com/avital/websocket-json-stream/blob/master/index.js#L17).

**Comment by gkubisa** [comment]
The problem is that [websocket-json-stream](https://www.npmjs.com/package/websocket-json-stream) emits 2 `end` events instead of 1. Please use [@teamwork/websocket-json-stream](https://www.npmjs.com/package/@teamwork/websocket-json-stream) instead. It sends only one `end` event and fixes a few other issues.
