### ISSUE TITLE
Use @teamwork/websocket-json-stream in textarea example

### ISSUE THREAD

**Issue by curran** [share/sharedb#280]
Since the [example in README.md uses @teamwork/websocket-json-stream](https://github.com/share/sharedb/pull/276/files), I thought it would make sense to also have the code examples use it. We can start with the textarea example, as it's been most recently updated, then perhaps update the others as well.

Although, there may be a better "best practice" nowadays, such as SockJS, I'm not really sure what the landscape looks like.

**Comment by gkubisa** [comment]
Yes, I think it would make sense to make the examples consistent with the Readme.

> Although, there may be a better "best practice" nowadays, such as SockJS, I'm not really sure what the landscape looks like.

WebSocket is supported by all major browsers, so in theory it should be all we need. Unfortunately, some corporate firewalls or proxies block WebSockets. If you care about those, then you should probably use SockJS, because it's not feasible to convince all those corporations to update their firewall rules to allow WebSockets. :-(
