### ISSUE TITLE
Queries multiply on client refresh (from example)

### ISSUE THREAD

**Issue by yarnball** [share/sharedb#300]
Hi,

I've been exploring middleware, using the "Leaderboard" example (here: https://github.com/share/sharedb/tree/master/examples/leaderboard).

However, I noticed that whenever I refresh the browser (client)- the number of "queries" multiplies significantly. Refreshing once, will triple each item I have used `connection().createSubscribeQuery`. Refreshing again and again multiplies even further.

Console:
![Screen Shot 2019-06-30 at 10 40 19 am](https://user-images.githubusercontent.com/13043067/60390845-8344de00-9b23-11e9-988e-0a5614e66f56.jpg)

I added this listening log at https://github.com/share/sharedb/blob/master/examples/leaderboard/server/index.js#L24

```
  share.listen(stream);
  share.use('query', (request, done) => {
      console.log('listening on....', request.collection)
      done()
  })
```
Is this going to have performance repercussions?

Is this expected behaviour, or the example is broken?

Thanks

**Comment by alecgibson** [comment]
You're seeing this because every time a user connects (`wss.on('connection', ...)`), you're adding a new middleware instance (`share.use`).  You'll presumably see one extra log message every time you refresh the page.

You should see the "normal" behaviour if you move the middleware declaration outside of the Websocket connection callback, so that the middleware is only ever registered once:

```javascript
share.use('query', (request, done) => {
  console.log('listening on', request.collection);
  done();
});

wss.on('connection', function(ws, req) {
  var stream = new WebSocketJSONStream(ws);
  share.listen(stream);
});
```

**Comment by yarnball** [comment]
Oh that makes sense. Thx for clarifying.

So nothing wrong with the example

Thank you
