### ISSUE TITLE
Mysterious Error: ShareDBError: Invalid op submitted. Op version newer than current snapshot

### ISSUE THREAD

**Issue by curran** [share/sharedb#422]
I'm noticing that this error pops up after I restart my ShareDB server.

I don't know why, and I'm opening this issue as a place to track down the root cause, as maybe others have faced this as well.

I have a hunch that ShareDB and/or the Mongo driver may have incremented the version in memory, and it hasn't yet been persisted to the database, and when a client (that is open from the previous incarnation of the server, and re-connects after the restart) submits an op the server fetches the outdated doc from the database and there is a version mismatch.

So I wonder, is there a better way to exit the process? Is there anything I can do to tell the system to flush all changes to the database before exiting?

Any insights would be most welcome!

**Comment by curran** [comment]
And by the way I made a change to the documents in MongoDB directly as well, via a Mongo query. I wonder if this may be the cause...

**Comment by curran** [comment]
I see in the `sharedb-mongo` doc:

>Never use the MongoDB driver or command line to directly modify any documents that ShareDB might create or edit.

OK, but why? What will happen exactly if you do? How should one go about adding a field to all documents?

**Comment by alecgibson** [comment]
With regards to editing documents directly in MongoDB, I guess it's _possible_, but it's dangerous, and requires an intimate understanding of ShareDB. The statement to not modify documents is mostly a catch-all, saying that ShareDB doesn't support arbitrary changes to the underlying data (ie all changes should be made through ShareDB), which I think is a fair statement.

Adding a new field can be done in a few ways. By far, the safest way is to just iterate over all your documents and add the field using ShareDB. Our team has a lazy migration mechanism that only migrates document schemas when the documents are accessed.

If you absolutely must update a document through MongoDB itself, you would need to:

 - take your server offline, so that no clients can submit requests, or are expecting to be kept up-to-date
 - run your query
 - force all clients to completely reset (ie `.destroy()` then `.fetch()`), because fetching ops **will not** correctly transform them up to the latest snapshot
 - note that (if you rely on history), your history will be broken (ie running all of your ops **will not** get you to your snapshot)

All in all, editing outside of ShareDB is probably a bad idea.

**Comment by alecgibson** [comment]
As far as your error goes, it's hard to say without more information. I can't immediately think off the top of my head why restarting the server should erroneously increment the client's version. As far as I'm aware, the version is only set when an op is acknowledged (ie has been committed), so killing the server before the commit just means that the client would try to submit its inflight op again.

**Comment by curran** [comment]
Thanks @alecgibson for responding here. Very interesting re: what needs to be done for direct MongoDB updates.

I'm pretty sure that it was the direct Mongo updates that indirectly caused those errors, rather than the server restart.

I changed my approach to, as you recommend, update the documents with ShareDB.

My solution for that looks something like this:
 * Query for all document IDs.
 * For each document (sequentially, async):
 * Fetch the ShareDB Doc, figure out what the new field values should be, and submit an op.

Here's the core of the solution, where `ids` is an array of document ids, and `updateScore` is a function that fetches that doc and submits the op.

```js
await ids.reduce(async (accumulator, id) => {
  await accumulator;
  return await updateScore(id);
}, {});
```

Context for the use case in case it's useful here: I want to periodically (e.g. hourly) update popularity scores for documents, similar to Reddit or HackerNews, using https://github.com/clux/decay .

The above solution works well enough for now, but I can't help imagine there may be a way to do it with fewer database invocations. Maybe one improvement on this could be to batch the document fetches by doing a pagination sort of query for, say, 1000 documents, then using `doc.ingestSnapshot` to instantiate the ShareDB document. I wonder, when you call `submitOp`, is that  _immediately_ persisted to the database, or is there a way to tell ShareDB "hold off on sending all those ops to the database" until we've processed all 1000 documents in that page, then tell ShareDB "OK, go ahead and submit them all, preferably in a single batched MongoDB call!" ?

**Comment by ericyhwang** [comment]
> Maybe one improvement on this could be to batch the document fetches by doing a pagination sort of query for, say, 1000 documents, then using `doc.ingestSnapshot` to instantiate the ShareDB document.

You can actually use the bulk fetch/subscribe/unsubscribe feature to do this:
```js
const doc1 = connection.get('foo', 'd1');
const doc2 = connection.get('foo', 'd2');

connection.startBulk();
// Issue all the fetches for this bulk request. Could use `async.each` for many docs in an array.
doc1.fetch(() => {});
doc2.fetch(() => {});
connection.endBulk();
```

That sends the fetch to the backend in a single `bf` (bulk fetch) request, and sharedb-mongo at least will handle fetching the batch of docs with one `find()` command.

> I wonder, when you call `submitOp`, is that immediately persisted to the database, or is there a way to tell ShareDB "hold off on sending all those ops to the database" until we've processed all 1000 documents in that page, then tell ShareDB "OK, go ahead and submit them all, preferably in a single batched MongoDB call!" ?

With sharedb-mongo, handling a submitted op is done in 2 steps: First commit the new op, then commit the updated snapshot. Since the op and snapshot are in two different collections, there's not a way to do that in bulk. There are Mongo transactions, but sharedb-mongo doesn't use them, and it's probably not a good idea to use transactions for a bulk operation anyways.

**Comment by curran** [comment]
Thank you so much @ericyhwang !

Closing as I've solved the issue for now, and there is a path forward for optimization using `startBulk` and `endBulk`.

I've also opened a new issue **Document Bulk Operations in README** https://github.com/share/sharedb/issues/425 .
