### ISSUE TITLE
ACK out of order

### ISSUE THREAD

**Issue by wangjianweiwei** [share/sharedb#495]
if the client receives ACK out of order, will the browser content be affect,For example, the client receives the ACK number of 55 before 54 , will that be a problem

**Comment by alecgibson** [comment]
Have you got a case of this happening?

**Comment by wangjianweiwei** [comment]
Yes, I've encountered this problem, but it's an accident. I'm using Python to perform similar functions. The server sends ACK to the client through the message queue, but the order before entering the queue may not be guaranteed. Have to come here for help.

**Comment by alecgibson** [comment]
Debugging a Python port is a bit beyond the scope of this library, I'm afraid. The best advice I can offer is to try and port the test suite, and get all your tests passing the same tests we run in JS.

**Comment by wangjianweiwei** [comment]
Thank you for your advice.

**Comment by ericyhwang** [comment]
Agreed that specific help with ports is beyond the scope of this library, but we can at least state what the JS library's behavior is.

It's not clear to us whether you are referring to snapshot versions (`v`) or to client sequence numbers (`seq`).

For `v` - The client ensures that each individual doc has [at most one in-flight op](https://github.com/share/sharedb/blob/e982eb623f932a962f560e52da438de2e60c9174/lib/client/doc.js#L78-L83), with subsequent ops [queued locally in the client](https://github.com/share/sharedb/blob/e982eb623f932a962f560e52da438de2e60c9174/lib/client/doc.js#L777-L780) until the in-flight op is ack'd. So it's impossible for a later op on that doc to be ack'd first, since ops are sent to the server one-by-one in strict order.

For `seq` - Since the client sequence number `seq` is incremented across all docs in a client, it is possible for `docId =def, seq = 55` to be ack'd before `docId = abc, seq = 54`, if they were ops on different docs. But that's ok, since ops on different docs are independent of each other.

Hope those bits of info help!
