### ISSUE TITLE
Is it possible to completely delete documents from the db

### ISSUE THREAD

**Issue by vkalpias** [share/sharedb#53]
I'd like to completely remove some documents from the db including their ops. Is that possible? 

Basically when we fetch a certain document, we check if it exists in the db and if not we create it with some initial data. Then when no one else is currently viewing this document we want to remove it from the database.

When I tried deleting the document from the db, when it's time to recreate it if someone tries to view it, I get CORRUPT DATA errors, probably because the document is still in memory?

**Comment by nateps** [comment]
No, it is not possible to use the ShareDB API to fully delete data and the op log is kept forever by default. 

As of ShareDB, the system should correctly deal with all cases where ops have been removed, and it will not get into a corrupt state anymore if you delete ops or a snapshot. Of course, if you delete ops and then a client reconnects needing those ops, you will break that client and it will be unable to submit any pending changes or bring itself up to date from its current state. So it is much safer to never delete any ops and if you are going to clean up ops and/or snapshots you'll need to ensure that no clients will never need them again or deal with the error appropriately.

Keeping issue open, because this should be well documented.

**Comment by dariocravero** [comment]
Assuming that your clients are correctly managing the state of the document, what would be the steps to delete a document?
Tried to hack my way into deleting docs naively deleting from `backend.db.docs` but that just created chaos. I imagine that there's more to cleanup than just that. Thanks! :)

**Comment by nateps** [comment]
Are you using ShareDB's memory DB and not backing it with a persistent database at all? It is not meant for production use, as if the server crashes, you will lose data.

**Comment by zag2art** [comment]
We periodically clean some of our collections, using the tool - https://github.com/dmapper/docclean

**Comment by dariocravero** [comment]
Hey @nateps, we're still staging it, but yes, we are considering using the in-memory DB for the time being.
The reason for this is that the collaboration layer isn't the source of truth for the shared text. We were using Firepad, but it was too controlling of our workflow. ShareDB gives us tonnes of freedom while building the flows. It's a longer story I'm happy to share but will probably derail the thread now :P.

The process we're currently using is: when a client goes online, it creates the shared doc if it doesn't exist (using the data from the PouchDB instance they have); otherwise it takes its changes (in this case, others are already collaborating on it).
Once the last client goes away from the document, we delete it. At that point, the doc got stored on their PouchDB.
If a user was working offline and when they came back online their version of the document is different than either the shared document or the main version; what they were working on is stored in their local log of changes so they can come back to it if needed. That's why, at least for now, we're OK with the shared server's data being ephemeral.

It is our first go with ShareDB and are loving it so far. I'm pretty sure we can make a better use of it and are open to any suggestions you have :).

Thanks @zag2art for referring us to that tool, will check it out!

**Comment by WinMinTun** [comment]
@dariocravero  @nateps  @zag2art @vkalpias Me too just using In memory database. My workflow is if there is no doc in sharedb, I load the doc into sharedb from DB. Then all the changes are in sharedb memory and after a user click 'save' button, save the QuillJS delta into DB (separate from sharedb). And many copies are left in sharedb memory and I need to clean them up. You know how can I check the last client goes away from a document? Any comments to my workflow? I do not store parmanetly Thanks, I m very new to this.

**Comment by bradisbell** [comment]
> No, it is not possible to use the ShareDB API to fully delete data and the op log is kept forever by default.

@nateps Your statement implies that it is *possible* to fully delete data, but it just isn't done in the default configuration.  How can we fully delete data?  Suppose I'm using ShareDB for many small transitory documents.  I might have millions over days, but might only have thousands in an active (not deleted) state at any given time.

> Are you using ShareDB's memory DB and not backing it with a persistent database at all? It is not meant for production use, as if the server crashes, you will lose data.

This is just fine for my use case, and I'm guessing others' as well.  I do plan on using ShareDBMingo to get better query support.

In any case, does ShareDB track anything on its own, or is it all just kept in the database?

**Comment by rkstedman** [comment]
If you want to permanently delete data, you can delete from your persistent datastore directly. For example, if you're using MongoDB you can delete the data by connecting to Mongo directly, not the ShareDB API. Note if you are going to delete data be sure that you clean up not just the document snapshot but all operations associated with that document.

**Comment by rkstedman** [comment]
Added documentation for this here: https://github.com/share/sharedb/pull/193/files

**Comment by alecgibson** [comment]
This isn't possible directly from ShareDB - delete from the data store as suggested above. Closing.
