### ISSUE TITLE
json0.compose without clone in the context of sharedb

### ISSUE THREAD

**Issue by happy15** [share/sharedb#547]
# Question

What if there is no clone of op1 in json0.compose(op1, op2) in the context of sharedb?

Instead of 
```
json.compose = function(op1,op2) {
  json.checkValidOp(op1);
  json.checkValidOp(op2);

  var newOp = clone(op1);

  for (var i = 0; i < op2.length; i++) {
    json.append(newOp,op2[i]);
  }

  return newOp;
};
```
we make it
```
json.compose = function(op1,op2) {
  json.checkValidOp(op1);
  json.checkValidOp(op2);

  for (var i = 0; i < op2.length; i++) {
    json.append(op1, op2[i]);
  }

  return op1;
};
```

# Background
A client submits an op with 4000 components (I know that's a lot, but let's accept it for now). According to doc._tryCompose in sharedb, this will cause about 8000000 (8 million) clones of op component object. This due that in json0.compose(op1, op2) op1 will be cloned and op1 is an ever growing list of op components. The math about clone here: (1+2+3+...+3999)=(1+3999)*3999/2~=8 million.

# Reasoning
From what I understand, json0.compose(op1, op2) itself is optional according to [ottypes doc](https://github.com/ottypes/docs), and return of naive concatenation of op1 and op2 without any composition should be valid. 

What's more is that in the context of sharedb, op1 is a list of clones of op components due implementation of json0.append(dest, c). Thus the in place mutation of op1 is restricted in the scope of sharedb rather than the app code that using sharedb.

# Concern
Is there anything I missed in the reasoning part in the context of sharedb?

**Comment by ericyhwang** [comment]
The direct answer to your question is that ShareDB and the OT types are two separate projects, with completely different sets of maintainers. So json0 likely does a clone for safety since it can't make assumptions about its inputs.

It may be possible to suggest a change to json0 to lazy clone only if needed, instead of always pre-cloning.

That said, with no changes to json0, there are a couple options to mitigate or avoid slowness from quadratic clones of thousands of op components:

1. If it's an option for you, pass all the op components in a single call to `doc.submitOp([opC1, opC2, opC3, opC4, ...])`. That results in only one pass of cloning, with number of clones scaling linearly with number of components.
2. Alternatively, if you do not want to compose at all, you can set `doc.preventCompose = true` - https://github.com/share/sharedb/blob/c945614800e45998c31d5b450dbfccb86efa9946/lib/client/doc.js#L103-L106

**Comment by happy15** [comment]
Finally we went with the first approach you suggested, thanks.
