### ISSUE TITLE
Backend.submit doesn't callback with snapshot

### ISSUE THREAD

**Issue by zmillman** [share/sharedb#67]
From https://github.com/share/sharedb/blob/master/lib/backend.js#L144
```js
// Submit an operation on the named collection/docname. op should contain a
// {op:}, {create:} or {del:} field. It should probably contain a v: field (if
// it doesn't, it defaults to the current version).
//
// callback called with (err, snapshot, ops)
Backend.prototype.submit = function(agent, index, id, op, callback) {
// ...
callback(err, request.ops);
```

**Comment by droganov** [comment]
Snapshot is there on "after submit", there is no operation undo if `next( err )` called.

**Comment by droganov** [comment]
@zmillman you ma close this. `Backend.apply` should be used instead `Backend.submit`

**Comment by nateps** [comment]
This is intentional. The general convention is that ShareDB middleware are called before a thing has happened, so at the time of submit, we have the op that was submitted, but the snapshot has not yet been fetched. `submit` only happens once per call to backend.submit, but the snapshot is actually fetched for each attempt to apply ops and commit, which may be retried multiple times in the rare but normal event of contention updating the same document from multiple clients at the same time. The snapshot is therefore first available in the `apply` middleware which is called for each try of the submit.

**Comment by nateps** [comment]
Issue is actually that the comment is wrong.
