### ISSUE TITLE
I create a sharedb example with quill.js

### ISSUE THREAD

**Issue by FTAndy** [share/sharedb#83]
I change the sharedb source file and change rich-text to the default ot-type, and change some rules that proper  to rich-text. It works well.

The repo:
https://github.com/FTAndy/sharedb-example
https://github.com/FTAndy/sharedb

If there is any favour I can do(add examples or add more ot-type), let me know. I will make a pr if is necessay.

**Comment by nateps** [comment]
Thanks for sharing!

I would definitely like to integrate the rich text type more officially into sharedb, though I don't think we should change the default type. My plan is actually to keep the top level type JSON and the JSON types have the ability to embed sub types within them. This requires some more testing, and I believe that the subtype support had some needed bug fixes that haven't been published yet, so that has to be done carefully. (Any type changes are of particular sensitivity, since we don't want the risk of corrupt data.)

**Comment by FTAndy** [comment]
@nateps hum, I am reading de source code to figure out how sharedb work, but the callback hell  is killing me. I have used promise to avoid callback hell for a while since I write javascript, but the source code is full with callback that disgusting me. I kind of want to strat writing a promise version sharedb to understanding the source code well. Wish me luck.

**Comment by FTAndy** [comment]
@sandro-pasquali maybe the sharedb repro has been update, whice causes the problem. use v0.11.35 version may help you. Let me check.

**Comment by sandro-pasquali** [comment]
@FTAndy Turns out that there is now an example of rich-text and quill: https://github.com/share/sharedb/tree/master/examples/rich-text

I think you inspired them! :)

**Comment by FTAndy** [comment]
@sandro-pasquali yeah, i find that too. I did not pay attention to the project for a while. Before May, it is a great project came from share.js without demo, so i write one. It just a little work i can do.

**Comment by pedrosanta** [comment]
So... if there's an example, it's a close then @nateps?

**Comment by solaiasp** [comment]
Hi..
I implemented share db rich-text collaborative editor. I added file write module when clinking save button.
[](![image](https://user-images.githubusercontent.com/31756643/31928376-932bd6c2-b8b5-11e7-93ff-2479bceb93c4.png))

I need to stop multiple edit control. and when I click Save button if there is a change in saved file need to show diff and merge it based on user convenience. 

And I need to display conflicts also.

**Comment by curran** [comment]
FWIW I also came across the `Agent closed due to error 88e61f71dd8341d91c266c177cf04493 { code: 4000, message: 'Received non-object message' }` error. It was indeed due to an old ShareDB version being installed. NPM by default installed `0.11.37`. The solution was to look at the [latest releases](https://www.npmjs.com/package/sharedb) and manually update package.json to use the latest 1.0 beta.
